WebApplication2/Models/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lolcschoolEntities : DbContext
    {
        public lolcschoolEntities()
            : base("name=lolcschoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<record> records { get; set; }
    }
}

WebApplication2/Models/Model1.Designer.cs
// T4 code generation is enabled for model 'E:\Kerja\MVC\WebApplication2\WebApplication2\Models\Model1.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

WebApplication2/Models/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

WebApplication2/Models/record.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class record
    {
        public int id { get; set; }
        public string coursename { get; set; }
        public Nullable<int> fee { get; set; }
    }
}

WebApplication2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebApplication2/Controllers/lolcController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Models;

namespace WebApplication21.Controllers
{
    public class lolcController : Controller
    {

        lolcschoolEntities db = new lolcschoolEntities();
        //
        // GET: /lolc/
        public ActionResult Index()
        {
            return View();
        }



        public ActionResult GetCourses()
        {
            using (lolcschoolEntities db = new lolcschoolEntities())
            {

                var courses = db.records.ToList();
                return Json(new { data = courses }, JsonRequestBehavior.AllowGet);

            }

        }

        [HttpGet]

        public JsonResult Edit(int Id)
        {
            var course = db.records.Where(a => a.id == Id).FirstOrDefault();
            return Json(course, JsonRequestBehavior.AllowGet);
        }



        public JsonResult Remove(int Id)
        {

            bool status = false;

            var course = db.records.FirstOrDefault(a => a.id == Id);

            if (course != null)
            {
                db.records.Remove(course);
                db.SaveChanges();
                status = true;
            }

            return new JsonResult { Data = new { status = status } };

        }


        public ActionResult save(record rec)
        {

            bool status = false;

            if (ModelState.IsValid)
            {
                using (lolcschoolEntities db = new lolcschoolEntities())
                {

                    if (rec.id > 0)
                    {
                        var v = db.records.Where(a => a.id == rec.id).FirstOrDefault();
                        if (v != null)
                        {
                            v.coursename = rec.coursename;
                            v.fee = rec.fee;
                            db.Entry(v).State = EntityState.Modified;
                        }
                    }
                    else
                    {
                        db.records.Add(rec);
                    }
                    db.SaveChanges();
                    status = true;
                }
            }
            return new JsonResult { Data = new { status = status } };
        }

    }
}

WebApplication2/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebApplication2/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebApplication2/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

WebApplication2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApplication2/Views/Shared/styles.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApplication2/Views/lolc/Index.cshtml
@{
    ViewBag.Title = "Course";
    Layout = "~/Views/Shared/styles.cshtml";
}

<div class="row">
    <div class="col-sm-4">
        <div class="container">
            @using (Html.BeginForm("save", "lolc", FormMethod.Post))
            {
                <div class="form-group">
                    <div>
                        <label class="form-label">Course Name</label>
                        <input type="text" id="name" name="name" class="form-control" placeholder="Name" />
                    </div>


                    <div>
                        <label class="form-label">Fee</label>
                        <input type="text" id="fee" name="fee" class="form-control" placeholder="Fee" />
                    </div>

                    <div>
                        <button type="button" id="save" class="btn btn-info" onclick="addProject()">Add</button>
                    </div>

                </div>

            }

        </div>

    </div>

    <div class="col-sm-8">
        <div class="panel-body">
            <table id="tbl-school" class="table table-bordered" cellspacing="0" width="100%" align="center">
                <thead>
                    <tr>
                        <th>Course Name</th>
                        <th>Fee</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                </thead>
            </table>

        </div>

    </div>

</div>


@section Scripts
{

    <script src="~/Scripts/jquery-1.10.2.js"></script>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>

    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>



    <script>

        getall();
        var isNew = true;

        function addProject() {

            var url = '';
            var data = '';
            var method;


            if (isNew == true) {
                url = '/lolc/save';
                data = "{coursename : '" + $('#name').val() + "',fee : '" + $('#fee').val() + "'}";
                method = 'POST';

            }
            else {
                url = '/lolc/save';
                data = "{coursename : '" + $('#name').val() + "',fee : '" + $('#fee').val() + "', id: '" + ID + "'}";
                method = 'POST';

            }


            $.ajax({

                type: method,
                url: url,
                dataType: 'JSON',
                contentType: "application/json; charset=utf-8",
                data: data,



                success: function (data) {
                    getall();
                    if (isNew) {
                        alert("Add");
                    }

                    else {
                        alert("Update");

                    }
                }
            });

        }


        function getall() {
            $('#tbl-school').dataTable().fnDestroy();
            $('#tbl-school').DataTable({

                "ajax": {

                    "url": '/lolc/GetCourses',
                    "type": "get",
                    "datatype": "JSON"

                },

                "columns":
                    [

                        { data: "coursename" },
                        { data: "fee" },
                        {
                            data: "id", "render": function (data) {
                                return '<button class= "btn btn-success" onclick = "get_course(' + data + ')"> Edit </button>';
                            }
                        },

                        {
                            data: "id", "render": function (data) {
                                return '<button class= "btn btn-danger" onclick = "get_delete(' + data + ')"> Delete </button>';
                            }
                        }
                    ]

            })

        }

        function get_course(id) {
            $.ajax({

                type: 'GET',
                url: '/lolc/Edit?Id=' + id,
                dataType: 'JSON',
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    isNew = false;

                    ID = data.id;
                    $('#name').val(data.coursename);
                    $('#fee').val(data.fee);

                }
            });

        }



        function get_delete(id) {

            $.ajax({

                type: 'POST',
                url: '/lolc/Remove?Id=' + id,
                dataType: 'JSON',
                contentType: "application/json; charset=utf-8",

                success: function (data) {
                    alert("deleted");
                    getall();


                }

            });
        }

    </script>

}